CI: set -e pipefail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,7 +54,7 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         python -m pip install wheel setuptools
-        python -m pip install numpy scipy matplotlib docutils "pytest<6" sphinx unittest-xml-reporting tinycc lxml h5py sphinx pyparsing html5lib reportlab pybind11 appdirs six numba mako ipython qtconsole xhtml2pdf unittest-xml-reporting pylint qt5reactor periodictable PyQt5
+        python -m pip install numpy scipy matplotlib docutils "pytest<6" sphinx unittest-xml-reporting tinycc lxml h5py sphinx pyparsing html5lib reportlab pybind11 appdirs six numba mako ipython qtconsole xhtml2pdf unittest-xml-reporting pylint qt5reactor periodictable PyQt5 uncertainties
 
     - name: Install pyopencl (Linux + macOS)
       if: ${{ matrix.os != 'windows-latest' }}
@@ -73,28 +73,6 @@ jobs:
         pip install git+https://github.com/bumps/bumps.git
         pip install git+https://github.com/SasView/sasmodels.git
 
-#    - name: Fetch sources for sibling projects
-#      run: |
-#        git clone --depth=50 --branch=master https://github.com/SasView/sasmodels.git ../sasmodels
-#        git clone --depth=50 --branch=master https://github.com/bumps/bumps.git ../bumps
-#
-#    - name: Build and install sasmodels
-#      run: |
-#        cd ../sasmodels
-#        rm -rf build
-#        rm -rf dist
-#        python setup.py clean
-#        python setup.py build
-#        python -m pip install .
-#
-#    - name: Build and install bumps
-#      run: |
-#        cd ../bumps
-#        rm -rf build
-#        rm -rf dist
-#        python setup.py clean
-#        python setup.py build
-#        python -m pip install .
 
     ### Actual building/testing of sasview
 
@@ -119,5 +97,7 @@ jobs:
       env:
         PYOPENCL_COMPILER_OUTPUT: 1
       run: |
+        # make sure the test will fail if the gui test doesn't work
+        set -e -o pipefail
         cd src/sas/qtgui
-        xvfb-run -a --server-args="-screen 0 1024x768x24" python GUITests.py || true
+        xvfb-run -a --server-args="-screen 0 1024x768x24" python GUITests.py
